In [1]:
import pandas as pd


data = pd.read_csv('CAX_Startup_Data.csv')
data.columns

Index(['Company_Name', 'Dependent-Company Status', 'year of founding',
       'Age of company in years', 'Internet Activity Score',
       'Short Description of company profile', 'Industry of company',
       'Focus functions of company', 'Investors', 'Employee Count',
       ...
       'Percent_skill_Data Science', 'Percent_skill_Business Strategy',
       'Percent_skill_Product Management', 'Percent_skill_Sales',
       'Percent_skill_Domain', 'Percent_skill_Law', 'Percent_skill_Consulting',
       'Percent_skill_Finance', 'Percent_skill_Investment', 'Renown score'],
      dtype='object', length=116)

In [2]:
data.corr()

,Internet Activity Score,Employee Count,Employees count MoM change,Last Funding Amount,Number of Co-founders,Number of of advisors,Team size Senior leadership,Industry trend in investing
Internet Activity Score,1.000000,0.100511,0.141396,0.029657,0.139881,0.089105,0.105978,0.041369
Employee Count,0.100511,1.000000,0.098178,0.371511,-0.021549,0.091659,0.497193,0.043491
Employees count MoM change,0.141396,0.098178,1.000000,0.120823,0.024138,0.080929,0.139582,0.199115
Last Funding Amount,0.029657,0.371511,0.120823,1.000000,0.013045,0.101469,0.376896,0.132535
Number of Co-founders,0.139881,-0.021549,0.024138,0.013045,1.000000,0.106028,0.138206,0.121460
Number of of advisors,0.089105,0.091659,0.080929,0.101469,0.106028,1.000000,0.303241,0.095711
Team size Senior leadership,0.105978,0.497193,0.139582,0.376896,0.138206,0.303241,1.000000,0.166963
Industry trend in investing,0.041369,0.043491,0.199115,0.132535,0.121460,0.095711,0.166963,1.000000

In [4]:
list1 = data['Dependent-Company Status'].to_list()
new_list = []

for x in list1:
    if x == 'Success':
        new_list.append(1)
    if x == 'Failed':
        new_list.append(0)
        
len(list1)

472

In [6]:
data['label'] = new_list

In [25]:
new = data[['label','Internet Activity Score','Last Funding Amount','Number of Co-founders','Number of of advisors','Team size Senior leadership']]
new

,label,Internet Activity Score,Last Funding Amount,Number of Co-founders,Number of of advisors,Team size Senior leadership
0,1,-1.0,450000.0,1,2,2
1,1,125.0,NaN,2,0,4
2,1,455.0,2350000.0,3,0,7
3,1,-99.0,10250000.0,2,0,4
4,1,496.0,5500000.0,1,1,8
...,...,...,...,...,...,...
467,0,-5.0,NaN,0,0,1
468,0,NaN,NaN,0,0,1
469,0,0.0,NaN,2,0,1
470,0,0.0,100000.0,3,2,1
471,0,11.0,120000.0,3,0,1

In [27]:
X = new[['Internet Activity Score','Last Funding Amount','Number of Co-founders','Number of of advisors','Team size Senior leadership']]
y = new.label

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [17]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred=logreg.predict(X_test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').